api_platform:
  title: 'Part-DB API'
  description: 'API of Part-DB'
  version: '0.1.0'

  formats:
    jsonld: ['application/ld+json']
    json:   ['application/json']
    jsonapi: ['application/vnd.api+json']

  docs_formats:
    jsonld: ['application/ld+json']
    jsonopenapi: ['application/vnd.openapi+json']
    html: ['text/html']
    json:   ['application/vnd.openapi+json']

  swagger:
    api_keys:
      # overridden in OpenApiFactoryDecorator
      access_token:
        name: Authorization
        type: header

  defaults:
    # TODO: Change this to true later. In the moment it is false, because we use the session in somewhere
    stateless: false
    cache_headers:
        vary: ['Content-Type', 'Authorization', 'Origin']
    extra_properties:
        standard_put: true
        rfc_7807_compliant_errors: true

    pagination_client_items_per_page: true # Allow clients to override the default items per page

  keep_legacy_inflector: false
  event_listeners_backward_compatibility_layer: false