api_platform:

  title: 'Part-DB API'
  description: 'API of Part-DB'

  version: '0.1.0'

#  eager_loading:
#    max_joins: 100

  keep_legacy_inflector: false

  swagger:
    api_keys:
      # overridden in OpenApiFactoryDecorator
      access_token:
        name: Authorization
        type: header

  defaults:
    # TODO: Change this to true later. In the moment it is false, because we use the session in somewhere
    stateless: false
    cache_headers:
        vary: ['Content-Type', 'Authorization', 'Origin']
    extra_properties:
        standard_put: true

    pagination_client_items_per_page: true # Allow clients to override the default items per page