twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig', 'form/extended_bootstrap_layout.html.twig', 'form/permission_layout.html.twig', 'form/filter_types_layout.html.twig', 'form/synonyms_collection.html.twig']

    paths:
        '%kernel.project_dir%/assets/css': css

    globals:
        allow_email_pw_reset: '%partdb.users.email_pw_reset%'
        locale_menu: '%partdb.locale_menu%'
        attachment_manager: '@App\Services\Attachments\AttachmentManager'
        label_profile_dropdown_helper: '@App\Services\LabelSystem\LabelProfileDropdownHelper'
        error_page_admin_email: '%partdb.error_pages.admin_email%'
        error_page_show_help: '%partdb.error_pages.show_help%'
        sidebar_tree_updater: '@App\Services\Trees\SidebarTreeUpdater'
        avatar_helper: '@App\Services\UserSystem\UserAvatarHelper'
        available_themes: '%partdb.available_themes%'
        saml_enabled: '%partdb.saml.enabled%'
        part_preview_generator: '@App\Services\Attachments\PartPreviewGenerator'

        # Bootstrap grid classes used for horizontal form layouts
        col_label: 'col-sm-3 col-lg-2'                      # The column classes for form labels
        col_input: 'col-sm-9 col-lg-10'                     # The column classes for form input fields
        offset_label: 'offset-sm-3 offset-lg-2'             # Offset classes for elements that should be aligned with the input fields (e.g., submit buttons)

when@test:
    twig:
        strict_variables: true
