when@dev:
    web_profiler:
        toolbar:
            ajax_replace: true

    framework:
        profiler:
            collect_serializer_data: true

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
