<?php

declare(strict_types=1);

namespace App\Tests\Migration;

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Platforms\MySQLPlatform;
use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Platforms\SQLitePlatform;
use Doctrine\DBAL\Schema\Schema;
use DoctrineMigrations\Version20260927120000;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;
use Psr\Log\NullLogger;

require_once dirname(__DIR__, 2).'/migrations/Version20260927120000.php';

final class ParameterDefinitionMigrationTest extends TestCase
{
    public static function platformProvider(): iterable
    {
        yield 'mysql' => [new MySQLPlatform(), 'JSON DEFAULT NULL', 'INT AUTO_INCREMENT NOT NULL'];
        yield 'postgresql' => [new PostgreSQLPlatform(), 'JSON DEFAULT NULL', 'GENERATED BY DEFAULT AS IDENTITY'];
        yield 'sqlite' => [new SQLitePlatform(), 'choices CLOB DEFAULT NULL', 'INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL'];
    }

    #[DataProvider('platformProvider')]
    public function testUpMigrationContainsPortableDefinitionAndRelationSql(
        AbstractPlatform $platform,
        string $expected_json_type,
        string $expected_identity,
    ): void {
        $sql = $this->migrationSql($platform, true);

        self::assertStringContainsString('CREATE TABLE parameter_definitions', $sql);
        self::assertStringContainsString($expected_json_type, $sql);
        self::assertStringContainsString($expected_identity, $sql);
        self::assertStringContainsString('definition_id', $sql);
        self::assertStringContainsString('ON DELETE RESTRICT', $sql);
        self::assertStringContainsString('parameter_definition_value_idx', $sql);
        if ($platform instanceof SQLitePlatform) {
            self::assertStringNotContainsString('eda_symbol_visibility, input_type', $sql);
            self::assertStringNotContainsString('input_type VARCHAR(16)', $this->parameterTableSql($sql));
            self::assertStringNotContainsString('choices CLOB', $this->parameterTableSql($sql));
        }
    }

    #[DataProvider('platformProvider')]
    public function testDownMigrationRemovesRelationBeforeDefinitionTable(
        AbstractPlatform $platform,
        string $_expected_json_type,
        string $_expected_identity,
    ): void {
        $sql = $this->migrationSql($platform, false);

        self::assertStringContainsString('parameters', $sql);
        self::assertStringContainsString('DROP TABLE parameter_definitions', $sql);
        self::assertStringEndsWith('DROP TABLE parameter_definitions', trim($sql));
        if ($platform instanceof SQLitePlatform) {
            self::assertStringNotContainsString('input_type VARCHAR(16)', $this->parameterTableSql($sql));
            self::assertStringNotContainsString('choices CLOB', $this->parameterTableSql($sql));
        }
    }

    public static function mergedColumnsProvider(): iterable
    {
        yield 'mysql' => [new MySQLPlatform(), 'deprecated_choices JSON DEFAULT NULL', 'alternative_names LONGTEXT DEFAULT NULL'];
        yield 'postgresql' => [new PostgreSQLPlatform(), 'deprecated_choices JSON DEFAULT NULL', 'alternative_names TEXT DEFAULT NULL'];
        yield 'sqlite' => [new SQLitePlatform(), 'deprecated_choices CLOB DEFAULT NULL', 'alternative_names CLOB DEFAULT NULL'];
    }

    /**
     * The former two migrations are merged into a single one: deprecated_choices and alternative_names
     * must be created together with the table, without any follow-up ALTER statement.
     */
    #[DataProvider('mergedColumnsProvider')]
    public function testMergedMigrationCreatesAllDefinitionColumnsInOneStatement(
        AbstractPlatform $platform,
        string $expected_deprecated_choices_sql,
        string $expected_alternative_names_sql,
    ): void {
        $sql = $this->migrationSql($platform, true);

        self::assertStringContainsString($expected_deprecated_choices_sql, $sql);
        self::assertStringContainsString($expected_alternative_names_sql, $sql);
        self::assertStringNotContainsString('ALTER TABLE parameter_definitions ADD', $sql);
    }

    private function migrationSql(AbstractPlatform $platform, bool $up): string
    {
        $connection = $this->createMock(Connection::class);
        $connection->method('getDatabasePlatform')->willReturn($platform);
        $migration = new Version20260927120000($connection, new NullLogger());

        if ($up) {
            $migration->up(new Schema());
        } else {
            $migration->down(new Schema());
        }

        return implode("\n", array_map(
            static fn ($query): string => $query->getStatement(),
            $migration->getSql(),
        ));
    }

    private function parameterTableSql(string $sql): string
    {
        $start = strpos($sql, 'CREATE TABLE parameters');
        self::assertNotFalse($start);

        return substr($sql, $start, (int) strpos($sql, ')', $start) - $start + 1);
    }
}
